name: CI

on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Enterprise RAG CI is working"